## 4 ways of dot products of Matrix

In [2]:
import numpy as np

In [3]:
matrix1 = np.arange(9).reshape(3,3)
matrix2 = np.arange(9).reshape(3,3)
# method 1
print(np.matmul(matrix1,matrix2))
print()
# method 2
print(np.dot(matrix1,matrix2))
print()
# method 3
print(matrix1@matrix2)
print()
# method 4
print(matrix1.dot(matrix2))
print()

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]



## Reshape Function using (-1,1)

In [4]:
array1 = np.arange(5).reshape(-1,1)
print(array1)
print()
array2 = np.arange(12).reshape(3,4)
print(array2.reshape(-1,1))
print()
array3 = np.arange(27).reshape(3,3,3)
print(array3.reshape(-1,1))

[[0]
 [1]
 [2]
 [3]
 [4]]

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]]


## copy function

In [6]:
a = np.arange(3)
print(a)
# assigning n = m creates another reference to array, if we change old it will reflect in new.
b = a
b[0] = 10
print(a)

# copy creates copy of matrix, if we changes old it wont reflect in new.
c = np.copy(a)
c[0] = 50
print("c", c)
print("a", a)

[0 1 2]
[10  1  2]
c [50  1  2]
a [10  1  2]


## view function

The numpy.view() is another way of viewing the array. It is the view of the new array with original data. This function will create the reference to an existing array. The changes will be reflected in the original array. 

In [8]:
array1 = np.arange(18).reshape(3, 6)

# changing dimension and datatype of array without creating a copy
view_array1 = array1.view(np.int32).reshape(6, 3)

# changes made reflects to a1 also
view_array1[0, 0] = -1

print(f"array 1: \ndimension : {array1.ndim} , data type : {array1.dtype}")
print(array1)

print(f"\nview_array: \ndimension : {view_array1.ndim} , data type : {view_array1.dtype}")
print(view_array1)

array 1: 
dimension : 2 , data type : int32
[[-1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

view_array: 
dimension : 2 , data type : int32
[[-1  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


## Broadcasting

In [13]:
array1 = np.arange(5).reshape(1, 5)
print()
array2 = np.arange(6).reshape(6, 1)
print()

print(array1)
print()
print(array2)
print()
print(array1 + array2)  # shape would be 4*3
print()
print(array1 * array2)  # shape would be 4*3
print()
print(5*array1)
print()
print(10+array1)



[[0 1 2 3 4]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]
 [ 0  5 10 15 20]]

[[ 0  5 10 15 20]]

[[10 11 12 13 14]]


In [15]:
a = np.arange(4).reshape(4, 1)
b = np.arange(3)
print(a)
print()
print(b)
print()

print(a+b)
print()

[[0]
 [1]
 [2]
 [3]]

[0 1 2]

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]



In [16]:
a = np.arange(12).reshape(3, 4)
b = np.arange(3)

# diffrent shapes throws error
print(a)
print(b)

print(a+b) 
# operands could not be broadcast together with shapes (3,4) (4,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 